server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/higo_hmall
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/,file:${file.upload-dir}
debug: false
logging:
  level:
    com.tanglinkai.mall: debug
mybatis-plus:
  global-config:
    db-config:
      table-prefix: wn_
      id-type: auto
    mapper-locations: classpath:/mapper/**/*.xml
file:
  upload-dir: D:\\Code\\higo-mall\\higo-mall-images\\