spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/higo_hmall
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp