server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/higo_hmall
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    web:
      resources:
        add-mappings: false
debug: false
logging:
  level:
    com.tanglinkai.mall: debug